environments:
  dev:
    requirements:
      - import: requirements.dev.txt

  ci:
    requirements:
      - import: requirements.ci.txt

requirements:
  - import: requirements.txt

pip_config_path: pip.conf
python_version: "3.9"

venv_directory: .venv
